name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Setup Go
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3

      # Install all the dependencies
      - name: Install dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go version
          go get -t .

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go test -v ./addresses/.
          go test -v ./helpers/.

      - name: Build webassembly
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          mkdir ./builds/webassembly/dist
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./builds/webassembly/dist/
          cd ./builds/webassembly/
          GOOS=js GOARCH=wasm go build -o ./dist/PandoraPay.wasm
